import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import missionsRouter from "./missions.js";
import sessionsRouter from "./sessions.js";
import proofsRouter from "./proofs.js";
import rewardsRouter from "./rewards.js";
import analyticsRouter from "./analytics.js";
import adminRouter from "./admin.js";
import extensionRouter from "./extension.js";
import sleepRouter from "./sleep.js";
import penaltiesRouter from "./penalties.js";
import strictnessRouter from "./strictness.js";
import timeEntriesRouter from "./time-entries.js";
import profileRouter from "./profile.js";
import skillsRouter from "./skills.js";
import aiMissionsRouter from "./ai-missions.js";
import inventoryRouter from "./inventory.js";
import streaksRouter from "./streaks.js";
import proofUploadsRouter from "./proof-uploads.js";
import shareRouter from "./share.js";
import feedbackRouter from "./feedback.js";
import invitesRouter from "./invites.js";
import endgameRouter from "./endgame.js";
import { adminLiveOpsRouter, userLiveOpsRouter } from "./live-ops.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/missions", missionsRouter);
router.use("/sessions", sessionsRouter);
router.use("/proofs", proofUploadsRouter);
router.use("/proofs", proofsRouter);
router.use("/rewards", rewardsRouter);
router.use("/analytics", analyticsRouter);
router.use("/admin", adminRouter);
router.use(extensionRouter);
router.use("/sleep", sleepRouter);
router.use("/penalties", penaltiesRouter);
router.use("/settings/strictness", strictnessRouter);
router.use("/time-entries", timeEntriesRouter);
router.use("/profile", profileRouter);
router.use("/skills", skillsRouter);
router.use("/ai-missions", aiMissionsRouter);
router.use("/inventory", inventoryRouter);
router.use("/streaks", streaksRouter);
router.use("/share", shareRouter);
router.use("/feedback", feedbackRouter);
router.use("/invites", invitesRouter);
router.use("/endgame", endgameRouter);
router.use("/admin/live-ops", adminLiveOpsRouter);
router.use("/live-ops", userLiveOpsRouter);

export default router;
