import { TuningDomain, ReviewCadence, type DomainWatchlistItem } from "./tuningTypes.js";

const WATCHLIST_ITEMS: DomainWatchlistItem[] = [
  {
    id: "econ-first-purchase-slow",
    domain: TuningDomain.ECONOMY,
    metricName: "economy.first_purchase_median_hours",
    label: "First purchase too slow",
    thresholdType: "above",
    thresholdValue: 72,
    whyItMatters: "Users who don't purchase early lose identity momentum and churn",
    recommendedResponse: "Review starter price band and Day 1 earning rate",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "econ-mint-rising",
    domain: TuningDomain.ECONOMY,
    metricName: "economy.mint_spend_ratio_7d",
    label: "Coins minted rising too fast",
    thresholdType: "above",
    thresholdValue: 3.0,
    whyItMatters: "High mint-to-spend ratio signals inflation risk",
    recommendedResponse: "Review reward bands and anti-inflation caps",
    cadence: ReviewCadence.DAILY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "econ-premium-adoption-low",
    domain: TuningDomain.ECONOMY,
    metricName: "economy.category_adoption.premium",
    label: "Premium item adoption too low",
    thresholdType: "below",
    thresholdValue: 5,
    whyItMatters: "Low premium adoption means aspiration pipeline is broken",
    recommendedResponse: "Review prestige item pricing and spotlight visibility",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "econ-save-spend-tension",
    domain: TuningDomain.ECONOMY,
    metricName: "economy.high_balance_no_spend_pct",
    label: "Under-spending with high balance",
    thresholdType: "above",
    thresholdValue: 30,
    whyItMatters: "Users saving but not spending suggests desire gap or unclear shop value",
    recommendedResponse: "Review shop item desirability and purchase UX",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "trust-followup-spike",
    domain: TuningDomain.TRUST,
    metricName: "trust.followup_rate_7d",
    label: "Follow-up rate spike",
    thresholdType: "above",
    thresholdValue: 30,
    whyItMatters: "High follow-up rate means users are confused or threshold is too strict",
    recommendedResponse: "Review confidence thresholds and proof guidance clarity",
    cadence: ReviewCadence.DAILY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "trust-reject-spike",
    domain: TuningDomain.TRUST,
    metricName: "trust.reject_rate_7d",
    label: "Reject rate spike",
    thresholdType: "above",
    thresholdValue: 15,
    whyItMatters: "High rejection frustrates users and degrades trust in the system",
    recommendedResponse: "Review trust thresholds and reason code messaging",
    cadence: ReviewCadence.DAILY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "trust-fallback-spike",
    domain: TuningDomain.TRUST,
    metricName: "trust.provider_fallback_rate",
    label: "Provider fallback rate spike",
    thresholdType: "above",
    thresholdValue: 20,
    whyItMatters: "High fallback means primary AI provider is unreliable",
    recommendedResponse: "Check AI provider status and cost tracking",
    cadence: ReviewCadence.DAILY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "trust-suspicious-spike",
    domain: TuningDomain.TRUST,
    metricName: "trust.suspicious_signal_rate",
    label: "Suspicious signal rate spike",
    thresholdType: "above",
    thresholdValue: 10,
    whyItMatters: "May indicate gaming attempt or overly sensitive anti-gaming rules",
    recommendedResponse: "Investigate specific signal types and user distribution",
    cadence: ReviewCadence.DAILY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "trust-reward-blocked-spike",
    domain: TuningDomain.TRUST,
    metricName: "trust.reward_blocked_rate",
    label: "Reward blocked rate spike",
    thresholdType: "above",
    thresholdValue: 10,
    whyItMatters: "Blocking too many rewards creates user frustration",
    recommendedResponse: "Review risk thresholds and escalation rules",
    cadence: ReviewCadence.DAILY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "personalization-ignored-high",
    domain: TuningDomain.PERSONALIZATION,
    metricName: "personalization.rec_ignored_rate",
    label: "Recommendation ignored rate too high",
    thresholdType: "above",
    thresholdValue: 60,
    whyItMatters: "Users ignoring recommendations means they are irrelevant or annoying",
    recommendedResponse: "Review recommendation weights and variety settings",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "personalization-comeback-weak",
    domain: TuningDomain.PERSONALIZATION,
    metricName: "personalization.comeback_conversion_7d",
    label: "Comeback conversion weak",
    thresholdType: "below",
    thresholdValue: 15,
    whyItMatters: "Low comeback conversion means re-engagement strategy is failing",
    recommendedResponse: "Review comeback path design and reward amounts",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "personalization-stalled-high",
    domain: TuningDomain.PERSONALIZATION,
    metricName: "personalization.stalled_users_pct",
    label: "Stalled users not recovering",
    thresholdType: "above",
    thresholdValue: 25,
    whyItMatters: "Many stalled users signals a progression or engagement problem",
    recommendedResponse: "Review personalization state graph transitions and next-action logic",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "liveops-participation-weak",
    domain: TuningDomain.LIVE_OPS,
    metricName: "liveops.event_participation_pct",
    label: "Event participation weak",
    thresholdType: "below",
    thresholdValue: 20,
    whyItMatters: "Low participation means events aren't appealing or visible enough",
    recommendedResponse: "Review event visibility, reward amounts, and timing",
    cadence: ReviewCadence.TWICE_WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "liveops-completion-weak",
    domain: TuningDomain.LIVE_OPS,
    metricName: "liveops.event_completion_pct",
    label: "Event completion weak",
    thresholdType: "below",
    thresholdValue: 30,
    whyItMatters: "Users start events but don't finish — too hard or too long",
    recommendedResponse: "Review event difficulty and duration requirements",
    cadence: ReviewCadence.TWICE_WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "liveops-fatigue-rising",
    domain: TuningDomain.LIVE_OPS,
    metricName: "liveops.event_skip_rate_trend",
    label: "Event fatigue indicators rising",
    thresholdType: "above",
    thresholdValue: 40,
    whyItMatters: "Rising skip rate means users are tired of events",
    recommendedResponse: "Reduce event frequency or increase event variety",
    cadence: ReviewCadence.MONTHLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "prestige-surface-ignored",
    domain: TuningDomain.PRESTIGE,
    metricName: "prestige.showcase_views_7d",
    label: "Prestige showcase ignored",
    thresholdType: "below",
    thresholdValue: 5,
    whyItMatters: "Low showcase views means prestige system isn't engaging users",
    recommendedResponse: "Review showcase placement, band thresholds, and highlight quality",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "prestige-history-weak",
    domain: TuningDomain.PRESTIGE,
    metricName: "prestige.history_views_7d",
    label: "History engagement weak",
    thresholdType: "below",
    thresholdValue: 5,
    whyItMatters: "Low history views means identity history isn't valuable to users",
    recommendedResponse: "Review history prominence and milestone surfacing",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "liveops-spotlight-weak",
    domain: TuningDomain.LIVE_OPS,
    metricName: "liveops.spotlight_purchase_uplift",
    label: "Spotlight conversion weak",
    thresholdType: "below",
    thresholdValue: 5,
    whyItMatters: "Spotlight events not driving purchases — wasted event slot",
    recommendedResponse: "Review featured category and event framing, consider mid-range items",
    cadence: ReviewCadence.TWICE_WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "personalization-next-action-weak",
    domain: TuningDomain.PERSONALIZATION,
    metricName: "personalization.next_action_ctr",
    label: "Next-action acceptance weak",
    thresholdType: "below",
    thresholdValue: 20,
    whyItMatters: "Users not following recommendations — content or relevance problem",
    recommendedResponse: "Review recommendation variety, state graph transitions, and stalled user handling",
    cadence: ReviewCadence.WEEKLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
  {
    id: "prestige-recognition-dilution",
    domain: TuningDomain.PRESTIGE,
    metricName: "prestige.recognition_slots_used_avg",
    label: "Recognition dilution risk",
    thresholdType: "above",
    thresholdValue: 5.5,
    whyItMatters: "If most users fill all 6 slots, recognition loses scarcity value",
    recommendedResponse: "Review recognition criteria or reduce max slots",
    cadence: ReviewCadence.MONTHLY,
    currentValue: null,
    isTriggered: false,
    lastCheckedAt: null,
  },
];

export function getAllWatchlistItems(): DomainWatchlistItem[] {
  return [...WATCHLIST_ITEMS];
}

export function getWatchlistByDomain(domain: TuningDomain): DomainWatchlistItem[] {
  return WATCHLIST_ITEMS.filter(w => w.domain === domain);
}

export function getTriggeredWatchlistItems(domain?: TuningDomain): DomainWatchlistItem[] {
  let items = WATCHLIST_ITEMS;
  if (domain) items = items.filter(w => w.domain === domain);
  return items.filter(w => w.isTriggered);
}

export function updateWatchlistValue(itemId: string, value: number): DomainWatchlistItem | null {
  const item = WATCHLIST_ITEMS.find(w => w.id === itemId);
  if (!item) return null;

  item.currentValue = value;
  item.lastCheckedAt = new Date().toISOString();

  switch (item.thresholdType) {
    case "above":
      item.isTriggered = value > item.thresholdValue;
      break;
    case "below":
      item.isTriggered = value < item.thresholdValue;
      break;
    case "change_rate":
      item.isTriggered = Math.abs(value) > item.thresholdValue;
      break;
  }

  return item;
}
