import { TuningDomain, ReviewCadence, type TuningLever } from "./tuningTypes.js";
import { ECONOMY_VERSION, REWARD_BANDS, ANTI_INFLATION, PRIORITY_MULTIPLIERS, DISTRACTION_MULTIPLIERS, SELLBACK_RATE_WEARABLE, SELLBACK_RATE_CAR } from "../economy/economyConfig.js";
import { TRUST_CONFIG } from "../trust/trustConfig.js";
import { PERSONALIZATION_CONFIG } from "../personalization/personalizationConfig.js";
import { LIVE_OPS_CONFIG_VERSION, LIVE_OPS_ECONOMY_LIMITS } from "../live-ops/liveOpsConfig.js";
import { PRESTIGE_CONFIG } from "../prestige/prestigeConfig.js";

export const TUNING_ENGINE_VERSION = "1.0.0";

export const DOMAIN_CONFIG_VERSIONS: Record<TuningDomain, () => string> = {
  [TuningDomain.ECONOMY]: () => ECONOMY_VERSION,
  [TuningDomain.TRUST]: () => TRUST_CONFIG.version,
  [TuningDomain.PERSONALIZATION]: () => PERSONALIZATION_CONFIG.version,
  [TuningDomain.LIVE_OPS]: () => LIVE_OPS_CONFIG_VERSION,
  [TuningDomain.PRESTIGE]: () => PRESTIGE_CONFIG.version,
  [TuningDomain.ONBOARDING]: () => "1.0.0",
};

export const DOMAIN_REVIEW_CADENCE: Record<TuningDomain, ReviewCadence> = {
  [TuningDomain.ECONOMY]: ReviewCadence.WEEKLY,
  [TuningDomain.TRUST]: ReviewCadence.WEEKLY,
  [TuningDomain.PERSONALIZATION]: ReviewCadence.WEEKLY,
  [TuningDomain.LIVE_OPS]: ReviewCadence.TWICE_WEEKLY,
  [TuningDomain.PRESTIGE]: ReviewCadence.BIWEEKLY,
  [TuningDomain.ONBOARDING]: ReviewCadence.BIWEEKLY,
};

export const DOMAIN_MIN_OBSERVATION_DAYS: Record<TuningDomain, number> = {
  [TuningDomain.ECONOMY]: 7,
  [TuningDomain.TRUST]: 7,
  [TuningDomain.PERSONALIZATION]: 5,
  [TuningDomain.LIVE_OPS]: 3,
  [TuningDomain.PRESTIGE]: 14,
  [TuningDomain.ONBOARDING]: 7,
};

export const TUNING_LEVERS: TuningLever[] = [
  {
    id: "economy.reward_band_trivial_max",
    domain: TuningDomain.ECONOMY,
    configPath: "REWARD_BANDS.trivial.maxReward",
    label: "Trivial reward max",
    description: "Maximum coins for trivial/low-effort missions",
    currentValueFn: () => REWARD_BANDS.trivial.maxReward,
    safeRange: { min: 5, max: 50 },
    observationWindowDays: 7,
    primaryMetric: "economy.coins_minted_daily",
    relatedMetrics: ["economy.mint_spend_ratio_7d", "activation.first_purchase_hours"],
    unsafeChanges: ["Setting above 50 inflates low-effort rewards"],
  },
  {
    id: "economy.reward_band_moderate_max",
    domain: TuningDomain.ECONOMY,
    configPath: "REWARD_BANDS.moderate.maxReward",
    label: "Moderate reward max",
    description: "Maximum coins for moderate-effort missions",
    currentValueFn: () => REWARD_BANDS.moderate.maxReward,
    safeRange: { min: 40, max: 150 },
    observationWindowDays: 7,
    primaryMetric: "economy.coins_minted_daily",
    relatedMetrics: ["economy.mint_spend_ratio_7d"],
    unsafeChanges: ["Setting above 150 creates inflation risk"],
  },
  {
    id: "economy.max_daily_missions",
    domain: TuningDomain.ECONOMY,
    configPath: "ANTI_INFLATION.maxDailyMissionsForReward",
    label: "Max daily rewarded missions",
    description: "Maximum missions per day that earn rewards",
    currentValueFn: () => ANTI_INFLATION.maxDailyMissionsForReward,
    safeRange: { min: 5, max: 20 },
    observationWindowDays: 7,
    primaryMetric: "economy.coins_minted_daily",
    relatedMetrics: ["core.mission_creation_rate"],
    unsafeChanges: ["Below 5 frustrates power users", "Above 20 enables grind-inflation"],
  },
  {
    id: "economy.streak_bonus_cap",
    domain: TuningDomain.ECONOMY,
    configPath: "ANTI_INFLATION.streakBonusMaxPct",
    label: "Streak bonus cap %",
    description: "Maximum streak bonus as percentage",
    currentValueFn: () => ANTI_INFLATION.streakBonusMaxPct,
    safeRange: { min: 5, max: 50 },
    observationWindowDays: 7,
    primaryMetric: "economy.coins_minted_daily",
    relatedMetrics: ["core.repeat_loop_7d"],
    unsafeChanges: ["Above 50% creates streak-dependent inflation"],
  },
  {
    id: "economy.sellback_rate_wearable",
    domain: TuningDomain.ECONOMY,
    configPath: "SELLBACK_RATE_WEARABLE",
    label: "Wearable sellback rate",
    description: "Percentage of original price returned on wearable sale",
    currentValueFn: () => SELLBACK_RATE_WEARABLE,
    safeRange: { min: 0.10, max: 0.40 },
    observationWindowDays: 14,
    primaryMetric: "economy.net_coin_delta_7d",
    relatedMetrics: ["economy.coins_spent_daily"],
    unsafeChanges: ["Above 40% enables buy-sell arbitrage"],
  },
  {
    id: "trust.confidence_high_min",
    domain: TuningDomain.TRUST,
    configPath: "TRUST_CONFIG.confidence.highMin",
    label: "High confidence threshold",
    description: "Minimum score for high-confidence approval",
    currentValueFn: () => TRUST_CONFIG.confidence.highMin,
    safeRange: { min: 0.60, max: 0.90 },
    observationWindowDays: 7,
    primaryMetric: "trust.followup_rate_7d",
    relatedMetrics: ["core.verdict_split", "trust.reject_rate_7d"],
    unsafeChanges: ["Below 0.60 approves low-quality proofs", "Above 0.90 rejects most proofs"],
  },
  {
    id: "trust.confidence_medium_min",
    domain: TuningDomain.TRUST,
    configPath: "TRUST_CONFIG.confidence.mediumMin",
    label: "Medium confidence threshold",
    description: "Minimum score for medium-confidence approval",
    currentValueFn: () => TRUST_CONFIG.confidence.mediumMin,
    safeRange: { min: 0.30, max: 0.60 },
    observationWindowDays: 7,
    primaryMetric: "trust.followup_rate_7d",
    relatedMetrics: ["trust.reject_rate_7d", "trust.confidence_distribution"],
    unsafeChanges: ["Below 0.30 enables borderline approvals"],
  },
  {
    id: "trust.suspicious_timing_max",
    domain: TuningDomain.TRUST,
    configPath: "TRUST_CONFIG.antiGaming.suspiciousTimingMaxPerTenMinutes",
    label: "Suspicious timing threshold",
    description: "Max proofs per 10 minutes before flagging",
    currentValueFn: () => TRUST_CONFIG.antiGaming.suspiciousTimingMaxPerTenMinutes,
    safeRange: { min: 2, max: 10 },
    observationWindowDays: 7,
    primaryMetric: "trust.suspicious_signal_rate",
    relatedMetrics: ["trust.followup_rate_7d"],
    unsafeChanges: ["Below 2 creates false positives for fast users"],
  },
  {
    id: "trust.followup_max_attempts",
    domain: TuningDomain.TRUST,
    configPath: "TRUST_CONFIG.followup.maxAttempts",
    label: "Follow-up max attempts",
    description: "Maximum follow-up attempts before rejection",
    currentValueFn: () => TRUST_CONFIG.followup.maxAttempts,
    safeRange: { min: 1, max: 5 },
    observationWindowDays: 7,
    primaryMetric: "trust.followup_rate_7d",
    relatedMetrics: ["personalization.followup_recovery_pct"],
    unsafeChanges: ["Above 5 lets poor proofs persist indefinitely"],
  },
  {
    id: "personalization.inactive_threshold_days",
    domain: TuningDomain.PERSONALIZATION,
    configPath: "PERSONALIZATION_CONFIG.momentum.inactiveThresholdDays",
    label: "Inactivity threshold (days)",
    description: "Days of no activity before user is classified inactive",
    currentValueFn: () => PERSONALIZATION_CONFIG.momentum.inactiveThresholdDays,
    safeRange: { min: 3, max: 14 },
    observationWindowDays: 7,
    primaryMetric: "personalization.stalled_users_pct",
    relatedMetrics: ["personalization.comeback_conversion_7d"],
    unsafeChanges: ["Below 3 days triggers over-eager re-engagement"],
  },
  {
    id: "personalization.consistent_streak_min",
    domain: TuningDomain.PERSONALIZATION,
    configPath: "PERSONALIZATION_CONFIG.discipline.consistentStreakMin",
    label: "Consistent streak minimum",
    description: "Minimum streak days for 'consistent' classification",
    currentValueFn: () => PERSONALIZATION_CONFIG.discipline.consistentStreakMin,
    safeRange: { min: 2, max: 14 },
    observationWindowDays: 7,
    primaryMetric: "personalization.next_action_ctr",
    relatedMetrics: ["core.repeat_loop_7d"],
    unsafeChanges: ["Below 2 makes consistency trivial"],
  },
  {
    id: "liveops.max_weekly_combined",
    domain: TuningDomain.LIVE_OPS,
    configPath: "LIVE_OPS_ECONOMY_LIMITS.maxWeeklyCombinedCoins",
    label: "Weekly combined event coin cap",
    description: "Maximum coins from events per week",
    currentValueFn: () => LIVE_OPS_ECONOMY_LIMITS.maxWeeklyCombinedCoins,
    safeRange: { min: 20, max: 150 },
    observationWindowDays: 7,
    primaryMetric: "liveops.event_participation_pct",
    relatedMetrics: ["economy.coins_minted_daily", "liveops.event_completion_pct"],
    unsafeChanges: ["Above 150 creates event-dependent inflation"],
  },
  {
    id: "liveops.max_comeback_coins",
    domain: TuningDomain.LIVE_OPS,
    configPath: "LIVE_OPS_ECONOMY_LIMITS.maxComebackCoins",
    label: "Max comeback reward",
    description: "Maximum coins for comeback events",
    currentValueFn: () => LIVE_OPS_ECONOMY_LIMITS.maxComebackCoins,
    safeRange: { min: 5, max: 50 },
    observationWindowDays: 7,
    primaryMetric: "liveops.comeback_event_conversion",
    relatedMetrics: ["personalization.comeback_conversion_7d"],
    unsafeChanges: ["Above 50 incentivizes deliberate inactivity"],
  },
  {
    id: "prestige.band_rising_threshold",
    domain: TuningDomain.PRESTIGE,
    configPath: "PRESTIGE_CONFIG.bandProgressionThresholds.rising",
    label: "Rising band threshold",
    description: "Score needed to reach Rising prestige band",
    currentValueFn: () => PRESTIGE_CONFIG.bandProgressionThresholds.rising,
    safeRange: { min: 10, max: 35 },
    observationWindowDays: 14,
    primaryMetric: "prestige.first_advancement_days",
    relatedMetrics: ["prestige.showcase_views_7d"],
    unsafeChanges: ["Below 10 makes Rising trivial"],
  },
  {
    id: "prestige.signal_weight_discipline",
    domain: TuningDomain.PRESTIGE,
    configPath: "PRESTIGE_CONFIG.signalWeights.discipline",
    label: "Discipline signal weight",
    description: "Weight of discipline signals in prestige score (must sum to 1.0 across all families)",
    currentValueFn: () => PRESTIGE_CONFIG.signalWeights.discipline,
    safeRange: { min: 0.10, max: 0.40 },
    observationWindowDays: 14,
    primaryMetric: "prestige.showcase_views_7d",
    relatedMetrics: ["prestige.first_advancement_days"],
    unsafeChanges: ["All weights must sum to 1.0", "Below 0.10 makes discipline irrelevant"],
  },
  {
    id: "prestige.max_showcase_highlights",
    domain: TuningDomain.PRESTIGE,
    configPath: "PRESTIGE_CONFIG.maxShowcaseHighlights",
    label: "Max showcase highlights",
    description: "Maximum highlights shown in showcase",
    currentValueFn: () => PRESTIGE_CONFIG.maxShowcaseHighlights,
    safeRange: { min: 1, max: 10 },
    observationWindowDays: 14,
    primaryMetric: "prestige.showcase_views_7d",
    relatedMetrics: ["prestige.repeat_showcase_visitors_pct"],
    unsafeChanges: ["Above 10 dilutes showcase impact"],
  },
];

export function getLeverById(leverId: string): TuningLever | undefined {
  return TUNING_LEVERS.find(l => l.id === leverId);
}

export function getLeversByDomain(domain: TuningDomain): TuningLever[] {
  return TUNING_LEVERS.filter(l => l.domain === domain);
}

export function getAllDomains(): TuningDomain[] {
  return Object.values(TuningDomain);
}
