import type { EventTemplate, EventTemplateId } from "./liveOpsTypes.js";

export const EVENT_TEMPLATES: Record<EventTemplateId, EventTemplate> = {
  weekly_focus_sprint: {
    id: "weekly_focus_sprint",
    layer: "weekly",
    name: "Weekly Focus Sprint",
    description: "Complete focus sessions this week to earn bonus coins.",
    defaultObjective: { type: "complete_sessions", count: 4, category: "any" },
    defaultRewardTemplateId: "completion",
    defaultDurationDays: 7,
    targetUserState: "active",
    economyCaution: "Max 50c/week from challenges. Does not stack with monthly milestone.",
    metricsToTrack: ["participation_rate", "completion_rate", "session_lift"],
  },

  weekly_discipline_push: {
    id: "weekly_discipline_push",
    layer: "weekly",
    name: "Weekly Discipline Push",
    description: "Submit approved proofs this week.",
    defaultObjective: { type: "submit_proofs", count: 2, category: "any" },
    defaultRewardTemplateId: "completion",
    defaultDurationDays: 7,
    targetUserState: "active",
    economyCaution: "Max 50c/week. Proofs must be approved (not just submitted).",
    metricsToTrack: ["participation_rate", "completion_rate", "proof_submission_lift"],
  },

  weekly_streak_builder: {
    id: "weekly_streak_builder",
    layer: "weekly",
    name: "Streak Builder Challenge",
    description: "Maintain a streak this week.",
    defaultObjective: { type: "maintain_streak", count: 5 },
    defaultRewardTemplateId: "completion",
    defaultDurationDays: 7,
    targetUserState: "active",
    economyCaution: "Max 50c. Streak must be real (verified via session/proof data).",
    metricsToTrack: ["participation_rate", "completion_rate", "streak_retention"],
  },

  weekly_skill_growth: {
    id: "weekly_skill_growth",
    layer: "weekly",
    name: "Skill Growth Challenge",
    description: "Complete missions in a specific skill category.",
    defaultObjective: { type: "complete_sessions", count: 2, category: "weakest" },
    defaultRewardTemplateId: "completion",
    defaultDurationDays: 7,
    targetUserState: "active",
    economyCaution: "Max 50c. Category should rotate weekly.",
    metricsToTrack: ["participation_rate", "completion_rate", "skill_xp_lift"],
  },

  weekly_proof_quality: {
    id: "weekly_proof_quality",
    layer: "weekly",
    name: "Proof Quality Challenge",
    description: "Submit a high-quality proof this week.",
    defaultObjective: { type: "submit_proofs", count: 1, threshold: 0.8 },
    defaultRewardTemplateId: "completion",
    defaultDurationDays: 7,
    targetUserState: "active",
    economyCaution: "Max 50c. Quality threshold should be achievable but meaningful.",
    metricsToTrack: ["participation_rate", "completion_rate", "avg_proof_quality"],
  },

  weekly_style_challenge: {
    id: "weekly_style_challenge",
    layer: "weekly",
    name: "Style Your World Challenge",
    description: "Purchase or equip an item this week.",
    defaultObjective: { type: "purchase_item", count: 1 },
    defaultRewardTemplateId: "participation",
    defaultDurationDays: 7,
    targetUserState: "active",
    economyCaution: "Max 25c participation reward. Does NOT discount items.",
    metricsToTrack: ["participation_rate", "purchase_lift", "equip_rate"],
  },

  milestone_level_gate: {
    id: "milestone_level_gate",
    layer: "monthly",
    name: "Monthly Level Milestone",
    description: "Reach the target level this month.",
    defaultObjective: { type: "reach_level", count: 3 },
    defaultRewardTemplateId: "milestone",
    defaultDurationDays: 30,
    targetUserState: "active",
    economyCaution: "Max 80c/month. Level target must be progressive (increase each month).",
    metricsToTrack: ["participation_rate", "completion_rate", "level_progression"],
  },

  milestone_mission_count: {
    id: "milestone_mission_count",
    layer: "monthly",
    name: "Mission Count Milestone",
    description: "Complete a total number of missions this month.",
    defaultObjective: { type: "total_missions", count: 10 },
    defaultRewardTemplateId: "milestone",
    defaultDurationDays: 30,
    targetUserState: "active",
    economyCaution: "Max 80c/month. Count must reflect real effort.",
    metricsToTrack: ["participation_rate", "completion_rate", "mission_throughput"],
  },

  milestone_skill_rank: {
    id: "milestone_skill_rank",
    layer: "monthly",
    name: "Skill Rank Milestone",
    description: "Reach a specific skill rank this month.",
    defaultObjective: { type: "skill_rank", count: 1 },
    defaultRewardTemplateId: "milestone",
    defaultDurationDays: 30,
    targetUserState: "active",
    economyCaution: "Max 80c. Can include cosmetic badge instead of full coin reward.",
    metricsToTrack: ["participation_rate", "completion_rate", "skill_rank_distribution"],
  },

  milestone_streak: {
    id: "milestone_streak",
    layer: "monthly",
    name: "Streak Achievement Milestone",
    description: "Achieve a significant streak this month.",
    defaultObjective: { type: "maintain_streak", count: 14 },
    defaultRewardTemplateId: "milestone",
    defaultDurationDays: 30,
    targetUserState: "active",
    economyCaution: "Max 80c. 14-day streak is hard — reward should feel earned.",
    metricsToTrack: ["participation_rate", "completion_rate", "streak_max"],
  },

  milestone_quarter_wrap: {
    id: "milestone_quarter_wrap",
    layer: "monthly",
    name: "Quarter Milestone",
    description: "Complete the quarterly progression milestone.",
    defaultObjective: { type: "reach_level", count: 8 },
    defaultRewardTemplateId: "milestone",
    defaultDurationDays: 30,
    targetUserState: "active",
    economyCaution: "Max 80c. Largest scheduled reward — ensure it requires real progress.",
    metricsToTrack: ["participation_rate", "completion_rate", "quarter_retention"],
  },

  spotlight_wardrobe: {
    id: "spotlight_wardrobe",
    layer: "monthly",
    name: "Wardrobe Spotlight",
    description: "Featured wardrobe collection this month.",
    defaultObjective: { type: "purchase_item", count: 1, category: "wearable" },
    defaultRewardTemplateId: "spotlight",
    defaultDurationDays: 14,
    targetUserState: "any",
    economyCaution: "Max 25c toward purchase. Does NOT give item free.",
    metricsToTrack: ["spotlight_views", "purchase_lift", "item_page_visits"],
  },

  spotlight_room: {
    id: "spotlight_room",
    layer: "monthly",
    name: "Room Environment Spotlight",
    description: "Featured room environment this month.",
    defaultObjective: { type: "room_upgrade", count: 1 },
    defaultRewardTemplateId: "spotlight",
    defaultDurationDays: 14,
    targetUserState: "any",
    economyCaution: "Max 25c. Spotlight creates desire, not discount.",
    metricsToTrack: ["spotlight_views", "purchase_lift", "room_score_lift"],
  },

  spotlight_car: {
    id: "spotlight_car",
    layer: "monthly",
    name: "Car Spotlight",
    description: "Featured vehicle this month.",
    defaultObjective: { type: "purchase_item", count: 1, category: "car" },
    defaultRewardTemplateId: "spotlight",
    defaultDurationDays: 14,
    targetUserState: "any",
    economyCaution: "Max 25c. Premium cars (5000c+) must NOT be trivialized.",
    metricsToTrack: ["spotlight_views", "purchase_lift", "car_equip_rate"],
  },

  spotlight_prestige: {
    id: "spotlight_prestige",
    layer: "monthly",
    name: "Prestige Tier Push",
    description: "Highlighting prestige benefits for users near threshold.",
    defaultObjective: { type: "earn_xp", count: 500 },
    defaultRewardTemplateId: "cosmetic_only",
    defaultDurationDays: 14,
    targetUserState: "active",
    economyCaution: "Zero coin reward. Prestige is its own reward.",
    metricsToTrack: ["prestige_tier_transitions", "xp_earning_lift"],
  },

  comeback_quick_return: {
    id: "comeback_quick_return",
    layer: "comeback",
    name: "Welcome Back — Quick Start",
    description: "One session to restart your journey.",
    defaultObjective: { type: "complete_sessions", count: 1, category: "any" },
    defaultRewardTemplateId: "comeback",
    defaultDurationDays: 7,
    targetUserState: "comeback",
    economyCaution: "Max 15c. Must be less than active user weekly reward.",
    metricsToTrack: ["comeback_3day_trigger_rate", "comeback_3day_conversion", "7day_retention"],
  },

  comeback_week_away: {
    id: "comeback_week_away",
    layer: "comeback",
    name: "Welcome Back — Pick Up Where You Left Off",
    description: "One approved proof to earn bonus coins and coaching.",
    defaultObjective: { type: "submit_proofs", count: 1, category: "any" },
    defaultRewardTemplateId: "comeback",
    defaultDurationDays: 14,
    targetUserState: "comeback",
    economyCaution: "Max 20c. Include coaching card, not just coins.",
    metricsToTrack: ["comeback_7day_trigger_rate", "comeback_7day_conversion", "7day_retention"],
  },

  comeback_extended: {
    id: "comeback_extended",
    layer: "comeback",
    name: "Fresh Start — Rebuild Your Momentum",
    description: "Complete 3 sessions to restart with bonus coins.",
    defaultObjective: { type: "complete_sessions", count: 3, category: "any" },
    defaultRewardTemplateId: "comeback",
    defaultDurationDays: 14,
    targetUserState: "comeback",
    economyCaution: "Max 30c. Reduced difficulty for first 3 missions.",
    metricsToTrack: ["comeback_14day_trigger_rate", "comeback_14day_conversion", "14day_retention"],
  },

  comeback_rebuild_streak: {
    id: "comeback_rebuild_streak",
    layer: "comeback",
    name: "Rebuild Your Streak",
    description: "Complete 3 sessions to restart your streak counter.",
    defaultObjective: { type: "complete_sessions", count: 3, category: "any" },
    defaultRewardTemplateId: "comeback",
    defaultDurationDays: 14,
    targetUserState: "comeback",
    economyCaution: "Max 25c. Streak resets to 0 regardless — this is about momentum, not gaming.",
    metricsToTrack: ["comeback_conversion", "streak_rebuild_rate"],
  },

  seasonal_banner: {
    id: "seasonal_banner",
    layer: "seasonal",
    name: "Seasonal Banner Event",
    description: "Seasonal theme event spanning multiple weeks.",
    defaultObjective: { type: "complete_sessions", count: 1 },
    defaultRewardTemplateId: "cosmetic_only",
    defaultDurationDays: 42,
    targetUserState: "any",
    economyCaution: "Seasonal events are thematic wrappers. Rewards come from sub-events.",
    metricsToTrack: ["seasonal_engagement", "purchase_lift", "retention_lift"],
  },
};
